language: node_js
node_js:
- '4.0'
- '9.0'
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: wwCPWGftSTLvwgxgGZCg39K9otbNDHj8slxffh/MTJT/pWYKnBqufQfe6WcCs06c5z6kTddKS7E/ao7jwVlB5/8pIlMzR9cSnCMpJtmh8mFJPSMEMuM4dOVuntNCS58iei7O3PZHuJmQxZY5r6Zrk2egAcsgsDzV6959rxrS3WI=
  file:
    - "mdast-util-heading-range.js"
    - "mdast-util-heading-range.min.js"
  on:
    tags: true
    node: '9.0'
